Employee_Management/Employee_Management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("Job_Holder/",include("Job_Holder.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Employee_Management/Job_Holder/urls.py
from django.urls import path
from Job_Holder import views
urlpatterns=[
    path("accounts/signup",views.SignUpView.as_view(),name="signup"),
    path("accounts/signin",views.LoginView.as_view(),name="signin"),
    path("accounts/signout",views.SignOut,name="signout"),
    path("home",views.IndexView.as_view(),name="home"),
    path("users/profile/add",views.CreateUserProfileView.as_view(),name="add-profile"),
    path("users/profile",views.ViewMyProfileView.as_view(),name="view-my-profile"),
    path("users/password/change",views.PasswordResetView.as_view(),name="password-reset"),
    path("users/profile/change/<int:user_id>",views.ProfileUpdateView.as_view(),name="profile-update"),
    path('post/comment/<int:post_id>',views.add_comment,name='add-comment'),
    path('users/pic/change<int:user_id>',views.ProfilePicUpdateView.as_view(),name="pic-change"),
    path('post/like/add/<int:post_id>',views.add_like,name="add-like"),
    path("users/profile/change/<int:user_id>", views.ProfileEditView.as_view(), name="profile-edit"),

]

Employee_Management/Job_Holder/models.py
from django.db import models
from django.contrib.auth.models import User



class UserProfile(models.Model):
    profile_pic=models.ImageField(upload_to="profile_pics",null=True)
    bio=models.CharField(max_length=120)
    phone=models.CharField(max_length=15)
    date_of_birth=models.DateField(null=True)
    options=(
        ("male", "male"),
        ("female", "female"),
        ("other", "other")
    )
    gender=models.CharField(max_length=12,choices=options,default="male")
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="users")

class JobDescription(models.Model):
    Name=models.CharField(max_length=120)
    description=models.CharField(max_length=230)
    Created_Date=models.DateField()
    Updated_Date=models.DateField()
    Unique_id=models.IntegerField()


def __str__(self):
    return self.title


class Comments(models.Model):
    job=models.ForeignKey(JobDescription, on_delete=models.CASCADE)
    comment=models.CharField(max_length=160)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

Employee_Management/Job_Holder/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from Job_Holder.models import UserProfile,JobDescription,Comments
class UserRegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=[
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2"
        ]

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput())


class UserProfileForm(ModelForm):
    class Meta:
        model=UserProfile
        exclude=("user",)
        # widget={
        #     "date_of_birth":forms.DateInput(attrs={"class":"form-control","type":"date"})
        # }



class PasswordRestForm(forms.Form):
    old_password=forms.CharField(widget=forms.PasswordInput)
    new_password=forms.CharField(widget=forms.PasswordInput)
    confirm_password=forms.CharField()




class JobForm(ModelForm):
    class Meta:
        model=JobDescription
        fields=["Name",
                "description",
                "Created_Date",
                "Updated_Date",
                "Unique_id"]
        widgets={
            "Name":forms.TextInput(attrs={"class":"form-control"}),
            "description":forms.Textarea(attrs={"class":"form-control"}),
            "Created_Date":forms.DateInput(attrs={"class":"form-control"}),
            "Updated_Date": forms.DateInput(attrs={"class": "form-control"}),
            "Unique_id": forms.TextInput(attrs={"class": "form-control"}),

        }


class CommentForm(ModelForm):
    class Meta:
        model=Comments
        fields=["comment"]

class ProfilePicUpdateForm(ModelForm):
    class Meta:
        model=UserProfile
        fields=[
            "profile_pic"
        ]
        widgets={
            "profile_pic":forms.FileInput(attrs={'class':'form-control'})
        }


Employee_Management/Job_Holder/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from Job_Holder.forms import UserRegistrationForm,LoginForm,UserProfileForm,PasswordRestForm,JobForm,CommentForm,ProfilePicUpdateForm
from django.views.generic import View,CreateView,FormView,TemplateView,UpdateView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login,logout
from Job_Holder.models import UserProfile,JobDescription,Comments
from django.contrib import messages



class SignUpView(CreateView):
    form_class = UserRegistrationForm
    template_name = "registration.html"
    model = User
    success_url = reverse_lazy("signup")





class LoginView(FormView):
    model=User
    template_name = "login.html"
    form_class = LoginForm

    def post(self, request, *args, **kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get("username")
            password=form.cleaned_data.get("password")
            user=authenticate(request,username=username,password=password)

            if user:
                print("success")
                login(request,user)
                return redirect("home")
            else:
                return render(request,self.template_name,{"form":form})


def SignOut(request,*args,**kwargs):
    logout(request)
    return redirect("signin")



class IndexView(CreateView):
    form_class = JobForm
    model = JobDescription
    template_name = "home.html"
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.author=self.request.user
        self.object = form.save()
        messages.success(self.request,"post has been saved")
        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        job=JobDescription.objects.all()
        context["jobs"]=job
        comment_form=CommentForm()
        context["comment_form"]=comment_form
        return context

    # def get_context_data(self,**kwargs):
    #     context=super().get_context_data(**kwargs)
    #     context["form"]=BlogForm()
    #     return context


class CreateUserProfileView(CreateView):
    model = UserProfile
    template_name = "addprofile.html"
    form_class = UserProfileForm
    success_url = reverse_lazy("home")

    def post(self, request, *args, **kwargs):
        form=self.form_class(request.POST,files=request.FILES)
        if form.is_valid():
            form.instance.user =request.user
            form.save()
            messages.success(self.request,"profile has been created")
            return redirect("home")
        else:
            return render(request,self.template_name,{"form":form})

    # def form_valid(self, form):
    #     form.instance.user=self.request.user
    #     messages.success(self.request,"profile has been created")
    #     self.object=form.save()
    #     return super().form_valid(form)




class ViewMyProfileView(TemplateView):
    template_name = "view-profile.html"



class PasswordResetView(FormView):
    template_name="passwordreset.html"
    form_class=PasswordRestForm

    def post(self, request, *args, **kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            oldpassword=form.cleaned_data.get("old_password")
            password1=form.cleaned_data.get("new_password")
            password2=form.cleaned_data.get("confirm_password")
            user=authenticate(request,username=request.user.username,password=oldpassword)

            if user:
                user.set_password(password2)
                user.save()
                messages.success(request,"password changed")
                return redirect("signin")
            else:
                messages.error(request,"invalid credentials")
                return render(request,self.template_name,{"form":form})


class ProfileUpdateView(UpdateView):
    form_class = UserProfileForm
    template_name = "profile-update.html"
    model = UserProfile
    success_url = reverse_lazy("home")
    pk_url_kwarg = "user_id"

    def form_valid(self, form):
        messages.success(self.request,"Your profile has been successfully updated")
        self.object=form.save()
        return super().form_valid(form)



def add_comment(request,*args,**kwargs):
    if request.method=='POST':
        blog_id=kwargs.get('post_id')
        blog=JobDescription.objects.get(id=blog_id)
        user=request.user
        comments=request.POST.get('comment')
        Comments.objects.create(blog=blog,comment=comments,user=user)
        messages.success(request,"Comment has been posted")
        return redirect('home')


class ProfilePicUpdateView(UpdateView):
    form_class = ProfilePicUpdateForm
    template_name = "profile-update.html"
    model = UserProfile
    success_url = reverse_lazy("home")
    pk_url_kwarg = "user_id"
    def form_valid(self, form):
        messages.success(self.request,"Profile pic has been updated")
        self.object=form.save()
        return super().form_valid(form)


def add_like(request,*args,**kwargs):
    blog_id=kwargs.get('post_id')
    blog=JobDescription.objects.get(id=blog_id)
    blog.liked_by.add(request.user)
    blog.save()
    return redirect("home")


class ProfileEditView(UpdateView):
    form_class = UserProfileForm
    template_name = "profile-edit.html"
    model = UserProfile
    success_url = reverse_lazy("home")
    pk_url_kwarg = "user_id"

    def form_valid(self, form):
        messages.success(self.request,"Your profile has been successfully edited")
        self.object=form.save()
        return super().form_valid(form)














Employee_Management/Job_Holder/templates/addprofile.html
{%extends 'base.html'%}
{%block body_block%}
<div class="row mt-lg-5">
    <div class="col-4"></div>
    <div class="col-4">
        <form action=""method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}
            <input type="Submit">
        </form>
    </div>
    <div class="col-4"></div>
</div>
{%endblock%}

Employee_Management/Job_Holder/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-info">
    <div class="container-fluid">
        <div style="height:75px;width:90px">
            <a class="navbar-brand" href="#">
                {%if request.user.users.profile_pic%}
                <img src="{{request.user.users.profile_pic.url}}" alt="..."
                     style="width:100%;height:100%">
                {%endif%}
            </a>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        ManageProfile
                    </a>
                    <ul class="dropdown-menu">
                        {%if request.user.users%}
                        <li><a class="dropdown-item" href="{%url 'view-my-profile'%}">View My Profile</a></li>
                        {%else%}
                        <li><a class="dropdown-item" href="{%url 'add-profile'%}">Add Profile</a></li>
                        {%endif%}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{%url 'password-reset'%}">Change password</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <ul>
                    <li><a class="dropdown-item" href="{%url 'signout'%}">Logout</a></li>
                </ul>
                <!--<button class="btn btn-outline-success" type="submit">Search</button>-->
            </form>
        </div>
    </div>
</nav>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages%}
            {%for msg in messages%}
            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <img src="..." class="rounded me-2" alt="...">
                    <strong class="me-auto">Bootstrap</strong>
                    <small>11 mins ago</small>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    Hello, world! This is a toast message.
                </div>
            </div>
            {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {% if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Holy guacamole!</strong> {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%endif%}
            {%endfor%}
            {%endif%}
        </div>
        <div class="col-4"></div>
    </div>
    {%block body_block%}

    {%endblock%}
</div>
</body>
</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</html>

Employee_Management/Job_Holder/templates/home.html
{%extends 'base.html'%}
{%block body_block%}
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <h1>Welcome user {{request.user}}</h1>
    </div>
    <div class="col-4"></div>
</div>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <form action="" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}
            <input type="Submit" value="post">
        </form>
    </div>
    <div class="col-4"></div>
</div>
{%for blog in blogs%}
<div class="row border mt-3">
    <div class="col-4"></div>
    <div class="col-4">
        <p>{JobDescription.Name}}</p>
        {%if blog.image%}
        <img src="{{blog.image.url}}" class="img-fluid" alt="...">
        <p>Posted_by {{JobDescription.description}}</p>
        <p>Created_by {{JobDescription.Created_Date}}</p>
        <p>Updated_by {{JobDescription.Updated_Date}}</p>
        <p>Given_by {{JobDescription.Unique_id}}</p>

        {%for comment in blog.comments_set.all%}
        <div>{{comment.comment}}</div>
        <div>{{comment.user}}</div>
        {%endfor%}
        <form action="{%url 'add-comment' blog.id%}"method="post">
            {%csrf_token%}
            {{comment_form.as_p}}
            <input type="Submit" class="btn btn-info" value="Add">
        </form>
        {%endif%}
        <div class="dropdown-item rounded d-flex justify-content-center align-items-center pointer text-muted p-1">
            <a href="{%url 'add-like' blog.id%}"><i class="fas-fa-thumps-up me-3 "</i></a>
            <p class="m-0">Like</p>
        </div>
    </div>
    <div class="col-4"></div>
</div>
{%endfor%}
{%endblock%}





Employee_Management/Job_Holder/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <h1>Login</h1>
            <form action=""method="post">
                {%csrf_token%}
                {{form.as_p}}
                <input type="Submit">
            </form>
        </div>
        <div class="col-4"></div>

    </div>
</div>

</body>
</html>

Employee_Management/Job_Holder/templates/passwordreset.html
{%extends 'base.html'%}
{%block body_block%}
<div class="row mt-lg-5">
    <div class="col-4"></div>
    <div class="col-4">
        <form action=""method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}
            <input type="Submit">
        </form>
    </div>
    <div class="col-4"></div>
</div>
{%endblock%}

Employee_Management/Job_Holder/templates/profile-edit.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action=""method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form.as_p}}
                <input type="Submit" value="Edit">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>
{%endblock%}

Employee_Management/Job_Holder/templates/profile-update.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action=""method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form.as_p}}
                <input type="Submit" value="Update">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>
{%endblock%}

Employee_Management/Job_Holder/templates/project-title edit.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action=""method="post" >
                {%csrf_token%}
                {{form.as_p}}
                <input type="Submit" value="Edit">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>
{%endblock%}

Employee_Management/Job_Holder/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action=""method="post">
                {%csrf_token%}
                {{form.as_p}}
                <input type="Submit">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>

</body>
</html>

Employee_Management/Job_Holder/templates/view-profile.html
{%extends 'base.html'%}
{%block body_block%}
<div class="row mt-lg-3">
    <div class="card" style="width: 18rem;">
        <img src="{{request.user.users.profile_pic.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{request.user}}</h5>
            <p class="card-text">{{request.user.users.bio}}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Phone {{request.user.users.phone}}</li>
            <li class="list-group-item">DOB {{request.user.users.date_of_birth}}</li>
        </ul>
        <div class="card-body">
            <a href="{%url 'profile-edit' request.user.users.id%}" class="card-link">Edit Profile</a>
            <a href="{%url 'profile-update' request.user.users.id%}" class="card-link">Update profile</a>
        </div>
    </div>
</div>
{%endblock%}